### ISSUE TITLE
Add in another reason macros are the bee's knees

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/ruby-oo-macros-readme#2]
When opening up a class, it is hard to realize that all of those setters/getters are kinda fluff. You don't want to have to sift through all the kinda BS-y methods to try and find the goodness. attr_accessible and friends allows you to get a high level overview of the class at the very beginning

Add this at the end of this readme in the final section "Using Macros is Usually Better"

**Comment by sullysaurus** [comment]
Updated.
